name: "Build"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@master
      with:
        remote: true
    - uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: |
        nix-shell
        ./build.sh
    - uses: EndBug/add-and-commit@v7
      with:
        author_name: Devin Singh
        author_email: drsingh2518@icloud.com
        default_author: user_info
        message: 'Build font'
        push: true
